language: php
php:
- 7.1
- 5.6
install: composer install
script: ./vendor/bin/phing test
after_success: ./vendor/bin/phing report-to-coveralls
notifications:
  email:
    recipients:
      - kristof@2dotstwice.be
  slack: cnet:UzmZZjVck1RNHTyrTSe6NTd9
